server:
  port: 8081
spring:
  application:
    name: "Mamivo"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:postgresql://localhost:5432/mamivo
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always