spring:
  application:
    name: "Mamivo"
  profiles:
    active: "prod"
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always


  docker:
    compose:
      enabled: false